// Font std();
// TimeLine T1(2004,0.25,&std);
Font font("Arial.ttf",30);
// Font Red();
Text txt("Hallo",0,200,&font);
// T1.addSpecialDate(2019,&Red);
// Red.setVar("color",(255,0,0));



// T1.goto(2020,10);
// [5]
// std.bez("size",70,7);
// [10]
[1]
txt.bez("text","Dies ist ein Testsatz... ein langweiliger dazu!\nFuer diesen Test ist das jedoch nicht von Bedeutung:)\n Aber hier ist genug platz fuer einen Guten Text!",5);
[7]
txt.bez("text","ENDE!",10);
// [12]
// T1.goto(2100,10);
// [11.5]
// font.bez("color",(255,0,0),2);
// [15]
// T1.removeSpecialDate(2019);


// [8]
// T1.bez("sections",3);

// [32]
